#config_version=6
mode:
  start_events: start_mode2
  stop_events: stop_mode2
  priority: 200
  start_priority: 1
  game_mode: False

slide_player:
  show_slide_mode2:
    slide_mode2:
      action: play
  show_slide_mode2_frame:
    slide_mode2_frame:
      action: play
  remove_slide_mode2_frame:
    slide_mode2_frame:
      action: remove
  show_anonymous_slide2:
    widgets:
        - type: text
          text: Anonymous Slide2

slides:
  slide_mode2:
  - type: text
    text: Slide Mode2
  slide_mode2_frame:
  - type: display
    width: 800
    height: 600
    source_display: frame_mode2
