#config_version=3

# The first line of every MPF config file needs to start with a hash sign,
# then config_version=3. When we add features that require changes to config
# files, we update the version number.

# You can add comments to config files by starting a line with a hash sign
# Comments are ignored by MPF and can be used for notes to yourself.


displays:
  default:
    width: 800
    height: 600
  dmd:
    width: 128
    height: 32


slides:
# The 'slides' section contains entries for named slides in your game. Then
# you can show any slide just by calling for that slide in a nice reusable way.

# Notice that each slide section is indented under the "slides:" section.

  slide1:  # This is the slide called "slide1"
    # Each slide has a list of "widgets" that are on it. Each widget is separated
    # by a dash.
    - type: text  # This is the first widget for slide1
      text: I AM A TEXT WIDGET ON SLIDE1 WITH DEFAULT SETTINGS
    - type: text  # This is the second widget
      text: HIT THE RIGHT ARROW KEY TO CONTINUE -->
      y: 33%
      animations:  # This widget has some animations for it.
        entrance:
          # The settings in the "entrance" section in the animations section
          # automatically start playing when the slide loads. Multiple steps in
          # the animation are also denoted with a dash.
          - property: opacity  # This step adjusts the "opacity" value of this widget.
            value: 0  # Zero means the widget is transparent
          - property: opacity  # This is the 2nd step in the animation. It also sets the opacity.
            value: 1  # But in this step, we're setting it back to 1 (opaque)
            repeat: true  # We add this so the animation repeats. Otherwise it would just run once.
    - type: rectangle
      color: red
      width: 800
      height: 600

  slide2:  # This is a different slide, called "slide2", etc.
    - type: text  # Every widget has a 'type', such as 'text', 'imagee', 'video', etc.
      text: I AM SLIDE 2. MY FONT SIZE IS 50
      font_size: 50  # Each type of widget has it's own settings. For example, font_size for text widgets
    - type: text
      text: HIT THE RIGHT ARROW KEY TO CONTINUE (MY FONT SIZE IS 15) -->
      y: 33%
    - type: text
      text: 2
      font_size: 150
      x: 700
      y: 500
    - type: ellipse
      width: 150
      height: 150
      x: 700
      y: 500
      color: darkblue

  slide3:
    - type: text
      text: I AM SLIDE 3. I AM RED
      font_size: 50
      color: ff0000  # You can use standard hex colors for widgets
    - type: text
      text: AGAIN, RIGHT ARROW -->
      y: 25%
      x: 66%
      style: typewriter
    - type: text
      text: ( <-- ALSO LEFT ARROW GOES BACK)
      y: 33%
      x: 7%
      animations:  # For this animation, we're animating the "x" property.
        entrance:  # "x" is the x position of the widget (like x,y coordinates)
          - property: x
            value: 5%  # In step 1, we set x to 5% (from 7% before)
            duration: .25s
          - property: x
            value: 7%  # In step 2, we set it back to 7%
            repeat: true  # and repeat!
            duration: 250ms

  slide4:
    - type: text
      text: THIS DEMO IS DRIVEN BY A STANDARD MPF CONFIG FILE
      font_size: 20
      color: ff0000
    - type: text
      text: IT'S IN THE FOLDER /mpf_mc/examples/demo/config/config.yaml
      font_size: 20
      color: 00ff00
      y: -50
    - type: line
      points: 100, 250, 100, 350, 700, 350, 700, 250
      close: yes
    - type: text
      text: KEEP GOING. (WE'LL REMOVE THIS MESSAGE FROM NOW ON)
      y: 75%
    - type: text
      text: JUST KNOW YOU CAN ALWAYS HIT THE ARROWS TO GO BACK AND FORTH
      y: 85%

  slide5:
    - type: text
      text: HEY, THAT WAS A SLIDE TRANSITION  # Transitions are set when a slide is requested (we'll get to that)
      font_size: 45
      color: ffaa00
    - type: text
      text: The transition was called "push", the direction is "right", and the duration is "1s"
      font_size: 20
      color: 00ff33
      y: -50
    - type: rectangle
      color: purple
      height: 100
      width: 800
    - type: rectangle
      color: 00ff33
      height: 200
      width: 600

  slide6:
    - type: points
      points: 100, 100, 150, 100, 200, 60, 400, 100, 136, 500
      size: 3
    - type: line
      points: 0, 0, 200, 200, 200, 400
      color: 00ff00
      thickness: 10
      close: true
    - type: bezier
      points: 800, 600, 200, 200, 800, 0
      color: pink
      thickness: 5
    - type: triangle
      points: 800, 600, 400, 600, 800, 400
      color: red
    - type: quad
      points: 100, 100, 110, 140, 200, 150, 220, 90
      color: lightblue
    - type: ellipse
      width: 200
      height: 200
      color: purple
      angle_start: 0
      angle_end: 90
    - type: rectangle
      x: 500
      y: 250
      width: 400
      height: 200
      color: orange
      corner_radius: 60
    - type: rectangle
      x: 700
      y: 100
      width: 100
      height: 200
      color: blue

  slide7:
    - type: dmd
      width: 640
      height: 160
#      color: ff00aa
#      source_display: dmd
#      shades: 16
#      gain: 2
#      bg_color: 303030
#      blur: .5
#      pixel_size: .7
#      dot_filter: false
    - type: text
      text: TRADITIONAL DMD AS A WIDGET
      y: 200
    - type: rectangle
      width: 642
      height: 162
      color: gray

  dmd_slide:
    - type: image
      image: jackpot
      fps: 20

  slide8:
    - type: dmd
      width: 640
      height: 160
      color: green
#      source_display: dmd
#      shades: 16
#      gain: 2
#      bg_color: 303030
      blur: .5
      pixel_size: .7
#      dot_filter: false
    - type: text
      text: SET THE COLOR TO WHATEVER YOU WANT
      y: 200
      color: green
    - type: rectangle
      width: 642
      height: 162
      color: gray

  slide9:
    - type: dmd
      width: 640
      height: 160
      color: green
#      source_display: dmd
#      shades: 16
#      gain: 2
#      bg_color: 303030
      blur: .5
      pixel_size: .7
      dot_filter: false
    - type: text
      text: REMOVE THE DOT FILTER
      y: 200
      color: green
    - type: rectangle
      width: 642
      height: 162
      color: gray

  slide10:
    - type: dmd
      width: 640
      height: 160
      color: green
#      source_display: dmd
      shades: 4
#      gain: 2
#      bg_color: 303030
      blur: .5
      pixel_size: .7
      dot_filter: false
    - type: text
      text: CLAMP DOWN TO 4 SHADES
      y: 200
    - type: rectangle
      width: 642
      height: 162
      color: gray

  slide11:
    - type: color_dmd
      width: 640
      height: 160
#      color: green
#      source_display: dmd
#      shades: 4
#      gain: 2
#      bg_color: 303030
      blur: .5
      pixel_size: .7
#      dot_filter: false
    - type: text
      text: COLOR DMD
      y: 200
    - type: rectangle
      width: 642
      height: 162
      color: gray

  slide12:
    - type: slide_frame
      name: left_frame
      width: 200
      height: 600
      x: 100
    - type: slide_frame
      name: center_frame
      width: 400
      height: 600
      x: 400
    - type: slide_frame
      name: right_frame
      width: 200
      height: 600
      x: 700

  left_slide1:
    - type: text
      text: 1
      style: chalk

  center_slide1:
    - type: text
      text: 2
      style: chalk

  right_slide1:
    - type: text
      text: 3
      style: chalk

  left_slide2:
    - type: ellipse
      color: green
      width: 200
      height: 200
    - type: rectangle
      color: yellow
      width: 200
      height: 600

  center_slide2:
    - type: ellipse
      color: pink
      width: 200
      height: 200
    - type: rectangle
      color: orange
      width: 600
      height: 600

  right_slide2:
    - type: ellipse
      color: red
      width: 200
      height: 200
    - type: rectangle
      color: blue
      width: 200
      height: 600

  center_slide3:
    - type: ellipse
      color: ffff00aa
      width: 100
      height: 100
      x: 100
      y: 400
    - type: image
      image: mpf_logo
    - type: ellipse
      color: 444444
      width: 390
      height: 300

  slide13:
    - type: text
      text: WIDGET ON VIDEO
      x: 650
      y: 100
      font_size: 30
      bold: true
      animations:
        event16:
          property: opacity
          value: 0
          duration: .5s
    - type: rectangle
      height: 100
      width: 300
      anchor_x: right
      x: 800
      y: 100
      color: 00000088
      animations:
        event16:
          property: opacity
          value: 0
          duration: .5s
    - type: video
      video: mpf_hq

# Now we're done with the slides config. The next section is the 'slide_player'.
# The slide_player is how we make slides show. They "play" when a certain mpf event is posted

slide_player:

  # There are lots of entries in here. One for each event.
  # So when the event 'mc_reset_phase_3' is posted, the slide_player shows slide1.
  mc_reset_phase_3:
    slide: slide1

  event1:
    slide: slide1

  event2:
    slide: slide2

  event3:
    slide: slide3

  event4:
    slide: slide4

  event5:
    slide: slide5
    transition:  # We can also specify slide transitions in the slide_player
      type: push

  event6:
    slide: slide6
    transition:
      type: rise_in

  event7:
    - slide: slide7
      transition:
       type: wipe
    - slide: dmd_slide
      target: dmd

  event8:
    slide: slide8

  event9:
    slide: slide9

  event10:
    slide: slide10

  event11:
    slide: slide11

  event12:
    - slide: slide12
    - slide: left_slide1
      target: left_frame
    - slide: center_slide1
      target: center_frame
    - slide: right_slide1
      target: right_frame

  event13:
    - slide: left_slide2
      target: left_frame
      transition:
        type: move_in
        direction: left
    - slide: center_slide2
      target: center_frame
      transition:
        type: move_in
        direction: top
    - slide: right_slide2
      target: right_frame
      transition:
        type: move_in
        direction: bottom

  event14:
    slide: center_slide3
    target: center_frame
    transition:
      type: swap

  event15:
    slide: slide13

widgets:
  score_group:
    - type: text
      text: 10,123,450
    - type: text
      text: 48,560,000
    - type: text
      text: "00"



text_styles:
  default:
    font_size: 20
  chalk:
    font_size: 50
#    font_name: Chalkduster
  typewriter:
    font_size: 30
#    font_name: Courier New


















mc_scriptlets:
  demo_driver.DemoDriver

keyboard:
  right:
    mc_event: next_slide
  left:
    mc_event: prev_slide


assets:
    images:
        default:
            load: preload
        preload:
            load: preload
            test_key: test_value
        on_demand:
            load: on_demand
        mode_start:
            load: mode_start
    videos:
        default:
            load: preload
        preload:
            load: preload
            test_key: test_value
        on_demand:
            load: on_demand
        mode_start:
            load: mode_start
